#!/usr/bin/env bash

# -------------------------------------------------------------------
#
# Copyright (c) 2012 Basho Technologies, Inc.
#
# This file is provided to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain
# a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------------

# The three function hooks are:
#   manage_CMDNAME_description
#   manage_CMDNAME_help
#   manage_CMDNAME
# where CMDNAME is the name of your command, and the filename

manage_a-sample-cmd_description () {
    echo "A sample command, showing how to make your own commands"
    return 0
}

manage_a-sample-cmd_help () {
    # You can do a heredoc style string instead of echos.
    # See the 'config' command for an example.
    echo
    echo "SYNOPSIS"
    echo " $bin_name ${ul}cluster${noul} a-sample-command ${ul}options${noul}"
    echo
    echo "DESCRIPTION"
    echo " This command just shows how to write a command. Read the source!"
    echo
    return 0
}

manage_a-sample-cmd () {
    if [ -z "$cluster_dir" ]; then
        error_msg "$cluster_name not found in RIAK_CLUSTERS environment variable."
        return 1
    fi

    echo "Cluster name: $cluster_name"
    echo "Cluster dir:  $cluster_dir"
    echo "Sample command arguments:"
    for i in $@; do
        echo "$i"
    done

    return 0
}

