#!/usr/bin/env bash

# -------------------------------------------------------------------
#
# Copyright (c) 2012 Basho Technologies, Inc.
#
# This file is provided to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain
# a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------------

manage_help_description () {
    echo "Get help on $bin_name commands"
    return 0
}

manage_help_help () {
    echo
    echo "SYNOPSIS"
    echo " $bin_name help ${ul}command${noul}"
    echo
    echo "DESCRIPTION"
    echo " Get help on a command, where command is one of the following:"

    pushd "${cmd_dir}" >/dev/null

    for cmd in !(*common); do
        echo "  ${cmd}"
    done
    echo

    popd >/dev/null # ${cmd_dir}

    return 0
}

manage_help () {
    local cmd cmd_index
    if [ $# -eq 0 ]; then
        echo "SYNOPSIS"
        echo " $bin_name ${ul}cluster${noul} command ${ul}options${noul}"
        echo
        echo "DESCRIPTION"
        echo " Where ${ul}command${noul} is one of the following:"

        pushd "${cmd_dir}" >/dev/null
        cmd_list=!(*common)

        for cmd in ${cmd_list[@]}; do
            . "${cmd_dir}/${cmd}"
            echo -n "  ${cmd}"
            let "cmd_space = 20 - ${#cmd}"
            while [ $cmd_space -gt 0 ]; do
                echo -n " "
                let "cmd_space = cmd_space - 1"
            done
            echo "$(manage_${cmd}_description)"
        done
        echo

        popd >/dev/null # ${cmd_dir}
        return 0
    else
        cmd=$1
        if [ ! -f "${cmd_dir}/$cmd" ]; then
            error_msg "Command $cmd not found. Cannot provide help information."
            return 1
        else
            . "${cmd_dir}/${cmd}"
            manage_${cmd}_help
            return $?
        fi
    fi
}
