#!/usr/bin/env bash

# -------------------------------------------------------------------
#
# Copyright (c) 2012 Basho Technologies, Inc.
#
# This file is provided to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain
# a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# -------------------------------------------------------------------

manage_riak_description () {
    echo "Run a 'riak' command on each node"
    return 0
}

manage_riak_help () {
    echo
    echo "SYNOPSIS"
    echo " $bin_name ${ul}cluster${noul} riak ${ul}options${noul}"
    echo
    echo "DESCRIPTION"
    echo " Run a 'riak' command on each node with the given ${ul}options${noul}."
    echo
    return 0
}

manage_riak () {
    if [ -z "$cluster_dir" ]; then
        error_msg "$cluster_name not found in RIAK_CLUSTERS environment variable."
        return 1
    fi

    for node_dir in $(ls -d "${cluster_dir}/${cluster_name}"/node*); do
        ${node_dir}/bin/riak $@
    done
}
